# Generated by Django 2.1.3 on 2018-12-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categroy',
            new_name='category',
        ),
    ]
